USCRN:
  description: Hourly historical weather data from USCRN 
  readme: https://www.ncei.noaa.gov/pub/data/uscrn/products/hourly02/readme.txt
  headers: https://www.ncei.noaa.gov/pub/data/uscrn/products/hourly02/headers.txt
  index: https://www.ncei.noaa.gov/pub/data/uscrn/products/hourly02/ 
  updates: https://www.ncei.noaa.gov/pub/data/uscrn/products/hourly02/updates/

NSRDB: https://nsrdb.nrel.gov/